config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: 'user/omniauth_callbacks' }

  root to: 'user#show'

  resource :user
  resource :search, only: :show, controller: :search
  resources :messages, except: %i[edit update]
  resources :playlists, only: %i[create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'
  belongs_to :playlist
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
end

app/models/spotify_playlist.rb
class SpotifyPlaylist
  def initialize(id:, name:, href:, image:, private_playlist:)
    @id = id
    @name = name
    @href = href
    @image = image
    @private_playlist = private_playlist
  end

  attr_reader :id, :name, :href, :images, :private_playlist

  def self.find_by_user(user:, page: 1, per: 25)
    user.renew_access_token

    response = HTTParty.get(
      "https://api.spotify.com/v1/me/playlists",
      query: { offset: (page - 1) * per, limit: per },
      headers: { 'Authorization': "Bearer #{user.access_token}" }
    )

    response['items'].map do |playlist_info|
      new(
        id: playlist_info['id'],
        name: playlist_info['name'],
        href: playlist_info['href'],
        image: playlist_info['images'].first,
        private_playlist: !playlist_info['public']
      )
    end
  end

  def self.find(id:, user:)
    user.renew_access_token

    playlist = HTTParty.get(
      "https://api.spotify.com/v1/playlists/#{id}",
      headers: { 'Authorization': "Bearer #{user.access_token}" }
    )

    return false if playlist['owner']['id'] != user.uid

    new(
      id: playlist['id'],
      name: playlist['name'],
      href: playlist['href'],
      image: playlist['images'].first,
      private_playlist: !playlist['public']
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:spotify]

  has_many :playlists
  has_many :messages, foreign_key: :recipient_id
  has_many :sent_messages, foreign_key: :sender_id

  def self.from_omniauth(auth)
    user = find_or_create_by(uid: auth.uid) do |user|
      user.uid = auth.uid
      user.email = auth.info.email
      user.name = auth.info.name
      user.country_code = auth.info.country_code
      user.href = auth.extra.raw_info.href
      user.password = Devise.friendly_token[0, 20]
    end

    user.update(
      access_token: auth.credentials.token,
      token_expires_at: Time.at(auth.credentials.expires_at),
      refresh_token: auth.credentials.refresh_token
    )

    user
  end

  def spotify_info
    renew_access_token

    response = HTTParty.get(
      'https://api.spotify.com/v1/me',
      headers: { 'Authorization' => "Bearer #{access_token}" }
    )

    update_user_info(
      followers: response.dig('followers', 'total'),
      image: response.dig('images', 0, 'url'),
      name: response['display_name']
    )

    response
  end

  def spotify_playlists(page: 1, per: 25)
    SpotifyPlaylist.find_by_user(user: self, page: page, per: per)
  end

  def renew_access_token
    return if token_expires_at > Time.now

    response = HTTParty.post(
      'https://accounts.spotify.com/api/token',
      body: {
        grant_type: 'refresh_token',
        refresh_token: refresh_token
      },
      headers: {
        'Authorization' => app_authorization_token
      }
    )

    update!(
      access_token: response['access_token'],
      token_expires_at: Time.now + response['expires_in'].seconds
    )
  end

  def app_authorization_token
    <<-TOKEN.squish
      Basic #{Base64.strict_encode64(
        Rails.application.credentials.spotify[:client_id] +
        ':' +
        Rails.application.credentials.spotify[:client_secret]
      )}
    TOKEN
  end

  private

  def update_user_info(followers:, image:, name:)
    update(
      name: name,
      followers: followers,
      image: image
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = current_user.messages.order(created_at: :desc)
  end

  def new
    @playlist = Playlist.find(params[:playlist_id])
    @message = Message.new(playlist_id: params[:playlist_id])
  end

  def create
    playlist = Playlist.find(message_params[:playlist_id])
    message = Message.new(
      sender: current_user,
      recipient: playlist.user,
      playlist: playlist,
      message: message_params[:message]
    )

    if message.save
      flash[:success] = 'Message Sent'
      redirect_to root_path
    else
      flash[:error] = 'Messafe not sent'
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:playlist_id, :message)
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def create
    if spotify_playlist = SpotifyPlaylist.find(id: params[:uid], user: current_user)
      playlist = Playlist.new(
        uid: spotify_playlist.id,
        name: spotify_playlist.name,
        href: spotify_playlist.href,
        user: current_user
      )
    end

    if playlist&.save
      flash[:success] = 'Playlist added'
    else
      flash[:error] = 'Error adding playlist'
    end

    redirect_to root_path
  end

  def destroy
    playlist = Playlist.find_by(id: params[:id], user: current_user)
    if playlist&.destroy
      flash[:success] = 'Playlist Removed'
    else
      flash[:error] = 'Error removing playlist'
    end

    redirect_to root_path
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def show
    if params[:search]
      @search_results = Playlist.where('name ILIKE ?', "%#{params[:search]}%")
    end
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def spotify
    @user = User.from_omniauth(request.get_header('omniauth.auth'))
    sign_in_and_redirect @user
  end

  # GET|POST /users/auth/twitter/callback
  def failure
    super
  end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action { current_user.spotify_info }

  def show
    @user = current_user
    @playlists = @user.spotify_playlists(page: params[:page]&.to_i || 1, per: params[:per]&.to_i || 25)
    @my_playlists = @user.playlists
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Venmanmusic
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if user_signed_in?
      .container
        .sidebar
          = link_to root_path, class: 'nav-item nav-profile' do
            = fa_icon('user', text: 'Profile')
          = link_to search_path, class: 'nav-item nav-search' do
            = fa_icon('search', text: 'Search')
          = link_to messages_path, class: 'nav-item nav-message' do
            = fa_icon('envelope', text: 'Messages')
          = link_to destroy_user_session_path, method: :delete, class: 'nav-item nav-log-out' do
            = fa_icon('sign-out-alt', text: 'Logout')

        .content
          = yield
    - else
      .homepage
        = yield

app/views/messages/index.haml
%h2
  Messages
%table
  %thead
    %tr
      %th
        Message
      %th
        Playlist they applied for
      %th
        Sender
      %th
        Sent At
  %tbody
    - @messages.each do |message|
      %tr
        %td
          #{message.message}
        %td
          #{message.playlist.name}
        %td
          #{message.sender.name}
        %td
          #{message.created_at}

app/views/messages/new.haml
%h5
  Apply for the playlist: #{@playlist.name}
= form_for @message do |f|
  = f.hidden_field :playlist_id, value: @message.playlist_id
  = f.text_area :message, rows: 10
  = f.submit 'Send'

app/views/search/index.html.haml
Hello
= link_to('Logout', destroy_user_session_path, method: :delete)

app/views/search/show.haml
.header
.middle
  = form_with url: search_path, method: :get, data: { remote: false } do |f|
    = f.text_field :search
    = f.submit 'Search'

  - if @search_results&.any?
    %table
      %thead
        %tr
          %th
            name
          %th
            href
          %th
      %tbody
        - @search_results.each do |playlist|
          %tr
            %td
              = playlist.name
            %td
              = playlist.href
            %td
              = link_to 'Apply', new_message_path(playlist_id: playlist.id)

app/views/user/show.haml
.header
  = image_tag @user.image
  %ul
    %li
      %h2.name
        = @user.name
    %li
      Listed playlists #{@user.playlists.count}
    %li
      Followers: #{@user.followers}
.middle
  - if params[:page]&.to_i&.>(1)
    = link_to 'Previous Page', root_path(page: params[:page].to_i - 1, per: 25)
  = link_to 'Next Page', root_path(page: params[:page]&.to_i&.+(1) || 2, per: 25)
  %table
    %thead
      %tr
        %th
          name
        %th
          href
        %th
          public
        %th
    %tbody
      - @playlists.each do |playlist|
        %tr
          %td
            = playlist.name
          %td
            = playlist.href
          %td
            = !playlist.private_playlist
          %td
            - if playlist.private_playlist
            - elsif @my_playlists.map(&:uid).include?(playlist.id)
              - my_playlist = @my_playlists.detect { |mp| mp.uid == playlist.id }
              = button_to 'Remove',
                          playlist_path(my_playlist.id),
                          action: :destroy,
                          id: my_playlist.id,
                          method: :delete,
                          form: { id: 'this' }
            - else
              = button_to 'Add', playlists_path, params: { uid: playlist.id }, form: { id: 'this' }
  -# %h5
  -#   picture
  -# %h5
  -#   listed playlists
  -# %h5
  -#   recent messages